[options]
db_host = False
db_port = False
db_user = odoo18
db_password = False
addons_path = /opt/odoo18/odoo/addons
admin_passwd = $pbkdf2-sha512$600000$ytlbq3XOmdMa41xrLQVgbA$G2N2GxgO7qXrBTYhJuKiXje/RzN2xKr5t1lgVu0jAOx0LRaCeQkDg23bOTRwlnJriaqwdjVxVD1Hc3GthPdB7A

