[options]
db_host = False
db_port = False
db_user = odoo18
db_password = False
addons_path = /opt/odoo18/odoo/addons
admin_passwd = $pbkdf2-sha512$600000$jhGCsLbWWuvd2xsDAEBorQ$Xqu8QF6q6dR4UPDA2INke0fzF89NdOrKNCSPYgFJdn0Itvwi56GS032VG7aOmwsdwRzxPPuQ/yoGdjJ0AKkOxQ
proxy_mode=True


